### ISSUE TITLE
oneproviders cannot register to onezone after upgrading from rc9 to rc11

### ISSUE THREAD

**Issue by stefanonicotri** [onedata/getting-started#19]
We have upgraded the OneZone from rc9 to rc11, keeping the same (working) configuration, but after the upgrade no OpeProvider seems to be able to register to our endpoint.
The procedure we have used to upgrade is as follows:

1. `mkdir rc11`
2. `cd rc11`
3. `git clone https://github.com/onedata/getting-started.git`
4. `cp OLD_DIR/docker-compose-onezone.yml rc11/getting-started/scenarios/3_0_oneprovider_onezone_multihost/`
5. `cd rc11/getting-started/scenarios/3_0_oneprovider_onezone_multihost/`
6. `sed s/rc9/rc11/ docker-compose-onezone.yml`
7. `./run_onedata.sh —clean`
8. We have verified that no container was running with docker ps -a
5. `./run_onedata.sh —zone`

After this, and after the usual autoconfiguration steps, the message 

> onezone-1                  | Congratulations! onezone has been successfully started.

appeared, and the OneZone was reachable via web (and everything seems to work fine).
Just no provider could register to it (while they can register to beta.onedata.org)

Could you please help us understanding what is wrong?
Cheers,
     stefano

**Comment by mariojmdavid** [comment]
can you (or others) confirm that the oneproviders are all at rc11?

**Comment by stefanonicotri** [comment]
Our oneprovider (the one we've tried to register to the onezone) is rc11. 
I don't know for sure about the others, but I think they are rc11 as well, since we were trying to upgrade the system to the most recent version.

**Comment by groundnuty** [comment]
@stefanonicotri 
I have investigated your machines. The provider works just fine. 
The problem is with your zone. When I start it using the compose config you were using the browser reports red https using certificates you supplied. The error that provider reports when it tries to register with your zone states  ```CERTIFICATE_VERIFY_FAILED```. 

Please double check your certificates. The paths alone in your docker compose config are fine.

When you comment out the certificates in your zone compose config and run it, your provider can register to it.

I hope that helps.

**Comment by stefanonicotri** [comment]
@groundnuty, thank you very much for your help.
The fact is that nothing has changed in our onezone machine when upgrading from rc9 to rc11, except the change `sed 's/rc9/rc11/' docker-compose-onezone.yml`. 
certificate paths are the same, and certificates and key still are in the stated locations.
how is it possible that previously working certificates are suddenly not accepted?

anyway, we have checked our certificates (certificate, CA certificate and key) and they are OK:

```
[onezone2 ~]# if [[ $(openssl x509 -noout -modulus -in /opt/onedata/onezone/ssl/etc/oz_worker/certs/gui_cert.pem | openssl md5) == $(openssl rsa -noout -modulus -in /opt/onedata/onezone/ssl/etc/oz_worker/certs/gui_key.pem | openssl md5) ]]; then echo OK; fi
OK
```

```
[onezone2 ~]# openssl verify -CAfile /opt/onedata/onezone/ssl/etc/oz_worker/cacerts/gui_cacert.pem /opt/onedata/onezone/ssl/etc/oz_worker/certs/gui_cert.pem
/opt/onedata/onezone/ssl/etc/oz_worker/certs/gui_cert.pem: OK
```

We have also substituted the CA certificate with one containing the whole chain, but providers are still not able to register to the onezone.
Have you modified anything about certificates in rc11 with respect to rc9?
If not, what else can cause this problem?
thanks

**Comment by ntritto** [comment]
I have the same error, i'm using the docker-compose-onezone.yml and docker-compose-oneprovider.yml  provided with  the version rc11 and scenario 3.0. I have run onezone on a first machine, after the successfully started message, i have run the script on the other machine, but i had this error message:
oneprovider-1                  | * service_oneprovider: register
oneprovider-1                  | 
oneprovider-1                  | Error: Service Error
oneprovider-1                  | Description: Action 'deploy' for a service 'oneprovider' terminated with an error.
oneprovider-1                  | Module: service_oneprovider
oneprovider-1                  | Function: register
oneprovider-1                  | Hosts: node1.oneprovider.localhost
oneprovider-1                  | For more information please check the logs.
oneprovider-1 exited with code 1

I tried the same test(on the same machines), just a couple of weeks ago, using rc9 release and both services were running with "successfully started" message.
Thank you for your consideration.
Nicola

**Comment by groundnuty** [comment]
@stefanonicotri 
The changed that fixes your issue, that I applied to your onezone installation was:

https://github.com/onedata/getting-started/commit/528e83cd4af89dc168b673f3a345c4705e44d4f6#diff-6931e4827a9c3819217156cb82ed09abR20

In your VM, at path 
~~~
/root/getting-started/scenarios/3_0_oneprovider_onezone_multihost/docker-compose-onezone.yml
~~~

Those lines have changed:
~~~
+    #- "/opt/onedata/onezone/ssl/etc/oz_worker/cacerts/gui_cacert.pem:/volumes/persistence/etc/oz_panel/certs/cacert.pem"
+    - "/opt/onedata/onezone/ssl/etc/oz_worker/cacerts/gui_cacert.pem:/volumes/persistence/etc/oz_panel/cacerts/cacert.pem"
+    - "/opt/onedata/onezone/ssl/etc/oz_worker/cacerts/gui_cacert.pem:/volumes/persistence/etc/oz_worker/cacerts/cacert.pem"
~~~

The cacert path changed and this information did not filter to me, to correct it in this repo, before I updated it to the new release. 

With those paths it all works. The alwasy up to date production configuration of our *beta.onedata.org* can be found here:
https://github.com/onedata/getting-started/blob/beta.onedata.org/scenarios/0_0_onedata_org/docker-compose-onezone.yml
