### ISSUE TITLE
20oneprovideronezone_scenario2

### ISSUE THREAD

**Issue by luda171** [onedata/getting-started#20]
Hi, 
I am trying to start  the provider service and I am getting:
Attaching to onezone-1
onezone-1                  | Starting oz_panel	[  OK  ]
onezone-1                  | 
onezone-1                  | HTTPSConnectionPool(host='127.0.0.1', port=9444): Max retries exceeded with url: /api/v3/onepanel/zone/configuration (Caused by ProxyError('Cannot connect to proxy.', error('Tunnel connection failed: 403 Forbidden',)))
onezone-1 exited with code 1

I do have no_proxy=”localhost,127.0.0.1”  configured as well. 
How this can be corrected?

**Comment by groundnuty** [comment]
@luda171 did you manage to resolve that issue? Also, you say you were trying to start a provider, while in fact the like *Attaching to onezone-1* says you are starting a onezone.
