### ISSUE TITLE
 3_0_oneprovider_onezone_multihost 

### ISSUE THREAD

**Issue by luda171** [onedata/getting-started#21]
Hi,
For the 3_0 oneprovider_onezone_multihost onezone startup
I got error:
Status: Image is up to date for docker.io/onedata/onezone:3.0.0-rc11
Creating onezone-1

ERROR: for node1.onezone.localhost  Cannot start service node1.onezone.localhost: failed to create endpoint onezone-1 on network 30oneprovideronezonemultihost_default: Error starting userland proxy: listen tcp 0.0.0.0:53: bind: address already in use
ERROR: Encountered errors while bringing up the project.

Documentation claims that port 53 is optional. How it can be configured as optional?

**Comment by groundnuty** [comment]
@luda171 did you manage to resolve that issue? In the docker-compose-oneprovider.yaml in scenario 3.0 directory, you can find a list of ports that are exposed, commenting out port 53 should be enough.
