### ISSUE TITLE
OpenId configuration

### ISSUE THREAD

**Issue by evasciacca** [onedata/getting-started#23]
Hello,

I have just updated the configurations to OneData rc14 and I am trying to configure the OpenId authentication. I have enabled the indigo IAM on the auth.conf and I have added the following lines to the docker-compose-onezone.yml:

```
volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "/home/cta/getting-started/scenarios/2_0_oneprovider_onezone/config_onezone/:/volumes/persistence"
    - "/home/cta/getting-started/bin/config/auth.conf:/var/lib/oz_worker/auth.conf"
```

But I still can not see the IAM authentication.

What am I doing wrong? The same procedure was working with OneData rc11...

Thank you in advance,

Eva.

**Comment by groundnuty** [comment]
@evasciacca 
assuming you followed the documentation on OpenID:
https://onedata.org/docs/doc/administering_onedata/openid_configuration.html
Please paste the content of your auth.conf with sensitive information removed.

**Comment by evasciacca** [comment]
Dear @groundnuty ,

yes, I followed the documentation. I send you the auth.conf file I am using with sensitive information removed.

Thank you,

Eva.
[auth.conf.txt](https://github.com/onedata/getting-started/files/957801/auth.conf.txt)

**Comment by evasciacca** [comment]
Dear @groundnuty ,

any news on this?

Thank you in advance,

Eva.

**Comment by evasciacca** [comment]
Ok, I think I have found the error! The configuration file should be named _auth.config_ NOT _auth.conf_

**Comment by groundnuty** [comment]
There was a typo in the docs for some time, sorry for that. I hope it worked. I'm closing this issue. If the problem persists please open a new one and reference this one.
