### ISSUE TITLE
Cannot start onezone with 17.06.0-beta2

### ISSUE THREAD

**Issue by stefanonicotri** [onedata/getting-started#30]
I tried to launch onezone with the new version 17.06.0-beta2, but I obtained the error

```
[root@onezone-test 3_0_oneprovider_onezone_multihost]# ./run_onedata.sh --zone
IMPORTANT: After each start wait for a message: Congratulations! onezone has been successfully started.
To ensure that the onezone is completely setup.
Pulling node1.onezone.localhost (onedata/onezone:17.06.0-beta2)...
17.06.0-beta2: Pulling from onedata/onezone
Digest: sha256:df8e320115ead4d71869de0fee43484054cc82ae2d9f15cf689828b0b8d9c35f
Status: Image is up to date for onedata/onezone:17.06.0-beta2
Creating onezone-INFN-BA ...
Creating onezone-INFN-BA ... done
Attaching to onezone-INFN-BA
onezone-INFN-BA            |
onezone-INFN-BA            | [Errno 39] Directory not empty: '/etc/init.d'
onezone-INFN-BA exited with code 1
```

the steps I've done are:

1. create a new CentOS 7 VM (8 CPU, 16GB of RAM)
2. yum update
3. install docker
4. install docker-compose
5. git clone this repo
6. modify docker-compose file to suit our site's needs
7. ./run_onedata.sh --zone

can you please provide help?
Cheers,
stefano

p.s. I attach the docker compose file and the content of /etc/init.d directory inside the docker conta
[Content_init.d_directory.txt](https://github.com/onedata/getting-started/files/1128111/Content_init.d_directory.txt)
[docker-compose-onezone.txt](https://github.com/onedata/getting-started/files/1128114/docker-compose-onezone.txt)

iner

**Comment by groundnuty** [comment]
@stefanonicotri this issue was resolved with beta6 release. please try it and reopen this issue if needed.

**Comment by caifti** [comment]
I've just hit the same issue with onedata/onezone:17.06.0-rc8:
Pulling node1.onezone.localhost (onedata/onezone:17.06.0-rc8)...
17.06.0-rc8: Pulling from onedata/onezone
Digest: sha256:7aa98da35928fa53745695b98b57638e5dfdd9c74795b72121fb9ccab582c619
Status: Image is up to date for onedata/onezone:17.06.0-rc8
Creating onezone-1 ... done
Attaching to onezone-1
onezone-1                  |
onezone-1                  | [Errno 39] Directory not empty: '/etc/init.d'
