### ISSUE TITLE
File management: Moving and copying - rc14

### ISSUE THREAD

**Issue by marcucci84** [onedata/getting-started#39]
I prepared a onedata demo in order to give to our users the opportunity  to test onedata.

One of our users inform me that it isn't possible to move files among the folders.

Version used: rc14 for oneprovider, rc16 for onezone.

**Comment by groundnuty** [comment]
rc14 can be considered quite obsolete now. lots of problems like this were
solved in the next versions. When giving demo, please use the newest
version always to ensure the best user experience. We tend to solve more
bugs, that we generate :-)

**Comment by groundnuty** [comment]
After coming talk with a developer. At the time of writing (onedata 7.06.0-rc2) all these works when done via oneclinet. In web interface, you can just copy, the 'move' operation is on our roadmap.

**Comment by marcucci84** [comment]
Thanks Michal for your answer. I will clarify this aspect to my users.

Regards
Nicola


Il 11/Set/2017 13:33, "Michal Orzechowski" <notifications@github.com> ha
scritto:
